version: "2.1"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - BOOKMARKER_HOST=0.0.0.0
      - BOOKMARKER_PORT=1323
      - BOOKMARKER_DB_USER=app
      - BOOKMARKER_DB_PASSWORD=password
      - BOOKMARKER_DB_HOST=db
      - BOOKMARKER_DB_PORT=5432
      - BOOKMARKER_DB_NAME=app
    expose:
      - 1323
    ports:
      - 1323:1323
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.2
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
