version: "2.1"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=1324
      - DB_USER=app
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app
    expose:
      - 1324
    depends_on:
      db:
        condition: service_healthy

  test-runner:
    build:
      context: .
      dockerfile: ./Dockerfile.func
    environment:
      - TEST_RUNNER_HOST=app
      - TEST_RUNNER_PORT=1324
      - TEST_RUNNER_DB_USER=app
      - TEST_RUNNER_DB_PASSWORD=password
      - TEST_RUNNER_DB_HOST=db
      - TEST_RUNNER_DB_PORT=5432
      - TEST_RUNNER_DB_NAME=app
    depends_on:
      app:
        condition: service_started
      db:
        condition: service_healthy

  db:
    image: postgres:13.2
    expose:
      - 5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
